databases:
  - name: jukeboxdb
    plan: free
    databaseName: dbjukebox
    user: jukebox

services:
  - type: web
    plan: free
    name: jukeBox
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn jukeBox.asgi:application -k uvicorn.workers.UvicornWorker' 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jukeBoxdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4